title: Anthony Reese
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Information Assurance, Cybersecurity
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reesea.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: _reesea
# github_username:  reesea

# Build settings
# theme: minima
# theme: jekyll-theme-hydeout
# plugins:
#  - jekyll-feed

remote_theme: fongandrew/hydeout
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"
sidebar_home_link: true
sidebar_about_link: "/about/"
sidebar_projects_link: "/projects/"
sidebar_notes_link: "/notes/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
